### ISSUE TITLE
data split

### ISSUE THREAD

**Issue by wanzhixiao** [RobinLu1209/STAG-GCN#4]
In geometric_dataset.py, i do not see how to split train and test dataset explictly, it just use a parameter type = "Train"

  def __init__(self, dataset_path, adjacency_matrix_path, dtw_matrix_path, node_num = 524, speed_mean = 29.0982979559, speed_std = 9.75304346669, his_num = 12, pred_num = 6, split_point_start = 0, split_point_end = 100*144, **type = "Train"**):

  ...
  print(f"INFO: {type} dataset shape is", self.dataset.shape)
  ...

and only print it,exactly,without use the parameter type to split train,val data? even worse,using the same dataset for traning and validation?

**Comment by RobinLu1209** [comment]
I'm very sorry for your ambiguity here. We use "split_point_start" and "split_point_end" to split different datasets.
